
-- Bronze
CREATE OR REPLACE TABLE azdb_sales_store.linio.bronze_compras (
    venta_id STRING,
    factura STRING,
    fecha_orden STRING,
    fecha_entrega STRING,
    fecha_envio STRING,
    estado STRING,
    cliente_code STRING,
    tipo_cliente STRING,
    nombres STRING,
    apellidos STRING,
    vendedor STRING,
    departamento STRING,
    metodo_pago STRING,
    subtotal STRING,
    tipo_compra STRING,
    fecha_carga TIMESTAMP
)
USING DELTA
LOCATION 'abfss://sales-store@adlssalesstoree.dfs.core.windows.net/bronze/compras';

CREATE OR REPLACE TABLE azdb_sales_store.linio.bronze_detalles (
    detalle_id STRING,
    factura STRING,
    num_tracking STRING,
    categoria STRING,
    subcategoria STRING,
    producto_id STRING,
    producto STRING,
    unidades STRING,
    precio_unitario STRING,
    oferta_id STRING,
    nombre_archivo STRING,
    fecha_carga TIMESTAMP
)
USING delta
LOCATION 'abfss://sales-store@adlssalesstoree.dfs.core.windows.net/bronze/detalles';

-- Silver
CREATE OR REPLACE TABLE azdb_sales_store.linio.silver_compras (
    venta_id            INTEGER,
    factura             STRING,
    tipo_compra         STRING,
    fecha_orden         DATE,
    fecha_entrega       DATE,
    fecha_envio         DATE,
    estado              INTEGER,
    cliente_id          INTEGER,
    vendedor            STRING,
    departamento        STRING,
    metodo_pago         STRING,
    dias_envio          INTEGER,
    grupo_dias_envio    STRING,
    periodo             DATE,
    fecha_actualizacion TIMESTAMP
)
USING DELTA
PARTITIONED BY (periodo)
LOCATION 'abfss://sales-store@adlssalesstoree.dfs.core.windows.net/silver/compras';




CREATE OR REPLACE TABLE azdb_sales_store.linio.silver_clientes (
    cliente_id INTEGER,
    tipo_documento STRING,
    num_documento STRING,
    nombre_completo STRING,
    tipo_cliente STRING,
    fecha_actualizacion TIMESTAMP
)
USING DELTA
LOCATION 'abfss://sales-store@adlssalesstoree.dfs.core.windows.net/silver/clientes';



CREATE OR REPLACE TABLE azdb_sales_store.linio.silver_productos (
    producto_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    producto STRING,
    subcategoria STRING,
    categoria STRING,
    fecha_actualizacion TIMESTAMP
)
USING DELTA
LOCATION 'abfss://sales-store@adlssalesstoree.dfs.core.windows.net/silver/productos';

CREATE OR REPLACE TABLE azdb_sales_store.linio.silver_detalles (
    detalle_id INT,
    factura STRING,
    producto STRING,
    producto_id INT,
    unidades INT,
    precio_unitario DOUBLE,
    subtotal DOUBLE,
    fecha_actualizacion TIMESTAMP
)
USING DELTA
LOCATION 'abfss://sales-store@adlssalesstoree.dfs.core.windows.net/silver/detalles';


--Gold
CREATE OR REPLACE TABLE azdb_sales_store.linio.gold_fact_compras (
    periodo DATE,
    venta_id INTEGER,
    factura STRING,
    tipo_compra STRING,
    fecha_orden DATE,
    fecha_entrega DATE,
    fecha_envio DATE,
    estado INTEGER,
    cliente_id INTEGER,
    vendedor STRING,
    departamento STRING,
    metodo_pago STRING,
    grupo_dias_envio STRING,
    detalle_id INTEGER,
    producto_id INTEGER,
    unidades INTEGER,
    subtotal DOUBLE,
    fecha_actualizacion TIMESTAMP
)
USING DELTA
PARTITIONED BY (periodo)
LOCATION 'abfss://sales-store@adlssalesstoree.dfs.core.windows.net/gold/fact_compras';








